name: Deploy Jekyll site to Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04 # from ubuntu-latest, 22 supports 2 years from 1/10/2025

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa
        with:
          bundler-cache: true
          cache-version: 0
      - name: Setup Pages
      - uses: actions/configure-pages@v4
        id: pages
      - name: Build with Jekyll
      # Builds site in directory specified by config.yml
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        # Automatically uploads an artifact from the 'docs' directory
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
      - uses: actions/deploy-pages@v4
        id: deployment
